---
title: "Assignment 2"
format:
  html:
    code-fold: true
    code-summary: "Show Code"
---

In this assignment, I analyzed the \`polls_us_election_2016\` dataset from the \`dslabs\` package and examined the missing values in the dataset.

## Importing the Dataset

```{r}
library(dslabs)
data("polls_us_election_2016")
df <- polls_us_election_2016
head(df)
```

## Defining Personal Variables

```{r}
my_first <- "Mert"
my_birth_year <- 2002
```

## Calculating k

```{r}
k <- (nchar(my_first) + my_birth_year) %% 15 + 8
k
```

## Displaying Rows Based on k

```{r}
if (k %% 2 == 0) {
  head(df, k)
} else {
  tail(df, k)
}
```

## Checking Missing Values

```{r}
total_na <- sum(is.na(df))
total_na
```

```{r}
na_per_column <- sort(colSums(is.na(df)), decreasing = TRUE)
head(na_per_column, 8)
```

## Creating a New Dataset

```{r}
new_data <- df
```

## Replacing Missing Values

```{}
{r}
for (col in names(new_data)) {
  
  # factorları character'a çevir
  if (is.factor(new_data[[col]])) {
    new_data[[col]] <- as.character(new_data[[col]])
  }

  if (is.numeric(new_data[[col]])) {
    new_data[[col]][is.na(new_data[[col]])] <- my_birth_year + k
  } else if (is.character(new_data[[col]])) {
    new_data[[col]][is.na(new_data[[col]])] <- paste0(my_first, "_", k)
  }
}
```

## Displaying the Updated Dataset

```{r}
if (k %% 2 == 0) {
  head(new_data, k)
} else {
  tail(new_data, k)
}
```

## Final Check

```{r}
sum(is.na(new_data))
anyNA(new_data)
```
